Repository LabKey/labkey-ui-components, pull requests merged in 2019-12, with the labels that each got.

#107 Item 6508: Permissions management components, models, and actions
  packages/components/README.md
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/ExpandableContainer.spec.tsx
  packages/components/src/components/ExpandableContainer.tsx
  packages/components/src/components/__snapshots__/ExpandableContainer.spec.tsx.snap
  packages/components/src/components/base/models/constants.ts
  packages/components/src/components/forms/PageDetailHeader.spec.tsx
  packages/components/src/components/forms/PageDetailHeader.tsx
  packages/components/src/components/forms/__snapshots__/PageDetailHeader.spec.tsx.snap
  packages/components/src/components/permissions/AddRoleAssignmentInput.tsx
  packages/components/src/components/permissions/PermissionAssignments.spec.tsx
  packages/components/src/components/permissions/PermissionAssignments.tsx
  packages/components/src/components/permissions/PermissionsContextProvider.tsx
  packages/components/src/components/permissions/PermissionsRole.spec.tsx
  packages/components/src/components/permissions/PermissionsRole.tsx
  packages/components/src/components/permissions/PrincipalDetailsPanel.spec.tsx
  packages/components/src/components/permissions/PrincipalDetailsPanel.tsx
  packages/components/src/components/permissions/RemovableButton.spec.tsx
  packages/components/src/components/permissions/RemovableButton.tsx
  packages/components/src/components/permissions/__snapshots__/PermissionAssignments.spec.tsx.snap
  packages/components/src/components/permissions/__snapshots__/PermissionsRole.spec.tsx.snap
  packages/components/src/components/permissions/__snapshots__/PrincipalDetailsPanel.spec.tsx.snap
  packages/components/src/components/permissions/__snapshots__/RemovableButton.spec.tsx.snap
  packages/components/src/components/permissions/actions.ts
  packages/components/src/components/permissions/models.spec.ts
  packages/components/src/components/permissions/models.ts
  packages/components/src/components/user/UserDetailHeader.spec.tsx
  packages/components/src/components/user/UserDetailHeader.tsx
  packages/components/src/components/user/__snapshots__/UserDetailHeader.spec.tsx.snap
  packages/components/src/components/user/actions.spec.ts
  packages/components/src/index.ts
  packages/components/src/stories/AssayDesignerPanels.tsx
  packages/components/src/stories/Cards.tsx
  packages/components/src/stories/DomainForm.tsx
  packages/components/src/stories/ExpandableContainer.tsx
  packages/components/src/stories/NavigationBar.tsx
  packages/components/src/stories/PageDetailHeader.tsx
  packages/components/src/stories/PermissionAssignments.tsx
  packages/components/src/stories/SearchResults.tsx
  packages/components/src/stories/UserDetailHeader.tsx
  packages/components/src/stories/mock.tsx
  packages/components/src/test/data/constants.ts
  packages/components/src/test/data/security-getPolicy.json
  packages/components/src/test/data/security-getPrincipals.json
  packages/components/src/test/data/security-getQueryDetailsPrincipals.json
  packages/components/src/test/data/security-getRoles.json
  packages/components/src/test/data/users.ts
  packages/components/src/testHelpers.ts
  packages/components/src/theme/container.scss
  packages/components/src/theme/index.scss
  packages/components/src/theme/permissions.scss
  packages/components/src/util/utils.spec.ts
  packages/components/src/util/utils.ts
  packages/components/yarn.lock
  packages/dependencies/package.json
Labels: TeamCity test review complete

#115 Remove @labkey/dependencies and move all dependencies to components/package.json
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/base/Progress.tsx
  packages/components/src/components/base/Tip.tsx
  packages/components/src/components/buttons/WizardNavButtons.tsx
  packages/components/src/components/lineage/Tag.tsx
  packages/components/src/components/navigation/ProductMenu.tsx
  packages/components/src/components/navigation/UserMenu.tsx
  packages/components/src/components/navigation/__snapshots__/ProductMenu.spec.tsx.snap
  packages/components/src/components/permissions/__snapshots__/PermissionsRole.spec.tsx.snap
  packages/components/src/components/permissions/__snapshots__/RemovableButton.spec.tsx.snap
  packages/components/src/stories/WizardNavButtons.tsx
  packages/components/src/typings/react-bootstrap.d.ts
  packages/components/tsconfig.json
  packages/components/yarn.lock
  packages/dependencies/README.md
  packages/dependencies/package.json
Labels: TeamCity test review complete

#118 Item 5511: UserMenu support for Sign In and Sign Out menu items
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/base/InsufficientPermissionsAlert.spec.tsx
  packages/components/src/components/base/InsufficientPermissionsAlert.tsx
  packages/components/src/components/base/__snapshots__/InsufficientPermissionsAlert.spec.tsx.snap
  packages/components/src/components/forms/input/UserSelectInput.tsx
  packages/components/src/components/navigation/UserMenu.tsx
  packages/components/src/components/navigation/__snapshots__/UserMenu.spec.tsx.snap
  packages/components/src/components/navigation/actions.ts
  packages/components/src/index.ts
  packages/components/src/theme/navbar.scss
Labels: TeamCity test review complete

#119 QueryGrid fix to remove extra call to reloadQueryGridModel when it is being unmounted
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/QueryGrid.tsx
  packages/components/src/util/URL.ts
Labels: TeamCity test review complete

#116 Change Sample Set to Sample Type in SM and add'l clean-up
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/base/SVGIcon.tsx
  packages/components/src/components/forms/PageDetailHeader.tsx
  packages/components/src/components/samples/SampleInsertPanel.tsx
  packages/components/src/components/samples/SampleSetDeleteConfirmModal.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.tsx
  packages/components/src/components/samples/SampleSetParentAliasRow.spec.tsx
  packages/components/src/components/samples/SampleSetParentAliasRow.tsx
  packages/components/src/components/samples/__snapshots__/SampleSetDetailsPanel.spec.tsx.snap
  packages/components/src/components/samples/__snapshots__/SampleSetParentAliasRow.spec.tsx.snap
  packages/components/src/components/samples/models.ts
  packages/components/src/components/search/SearchResultCard.tsx
  packages/components/src/components/search/SearchResultsPanel.tsx
  packages/components/src/constants.ts
  packages/components/src/stories/SearchResults.tsx
  packages/components/src/theme/samples.scss
Labels: code review complete, needs TeamCity test review, needs issue verification

#121 Item 6392: Changes to support session timeout handling in SM app
  README.md
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/actions.ts
  packages/components/src/components/base/ConfirmModal.spec.tsx
  packages/components/src/components/base/ConfirmModal.tsx
  packages/components/src/components/base/InsufficientPermissionsAlert.spec.tsx
  packages/components/src/components/forms/FieldEditTrigger.tsx
  packages/components/src/components/forms/QueryInfoForm.tsx
  packages/components/src/components/forms/input/LookupSelectInput.tsx
  packages/components/src/components/permissions/PermissionsContextProvider.tsx
  packages/components/src/components/samples/SampleDeleteConfirmModal.spec.tsx
  packages/components/src/components/samples/SampleDeleteConfirmModal.tsx
  packages/components/src/components/samples/SampleInsertPanel.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.spec.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.tsx
  packages/components/src/components/samples/actions.ts
  packages/components/src/components/user/UserProfile.tsx
  packages/components/src/query/api.ts
Labels: TeamCity test review complete, code review complete
