Repository LabKey/labkey-ui-components, pull requests merged in 2020-01, with the labels that each got.

#126 Secure Issue 39171: Workflow jobs are missing some search indexes
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/util/URLResolver.ts
Labels: code review complete, issue verification complete

#133 Issues 38823 and 38824: QueryGrid paging updates for page size and "Jump To First/Last Page" options
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/actions.ts
  packages/components/src/components/QueryGrid.tsx
  packages/components/src/components/__snapshots__/QueryGridPanel.spec.tsx.snap
  packages/components/src/components/base/Tip.tsx
  packages/components/src/components/gridbar/Export.tsx
  packages/components/src/components/gridbar/PageSizeSelector.spec.tsx
  packages/components/src/components/gridbar/PageSizeSelector.tsx
  packages/components/src/components/gridbar/QueryGridBar.spec.tsx
  packages/components/src/components/gridbar/QueryGridBar.tsx
  packages/components/src/components/gridbar/QueryGridPaging.spec.tsx
  packages/components/src/components/gridbar/QueryGridPaging.tsx
  packages/components/src/components/gridbar/ViewSelector.tsx
  packages/components/src/components/gridbar/__snapshots__/PageSizeSelector.spec.tsx.snap
  packages/components/src/components/gridbar/__snapshots__/QueryGridBar.spec.tsx.snap
  packages/components/src/components/gridbar/__snapshots__/QueryGridPaging.spec.tsx.snap
  packages/components/src/models.ts
  packages/components/src/query/api.ts
  packages/components/src/stories/QueryGridPanel.tsx
  packages/components/src/stories/mock.tsx
  packages/components/src/test/data/mixtures-getQueryPaging.json
  packages/components/src/theme/form.scss
  packages/components/src/theme/grid.scss
Labels: TeamCity test review complete, issue verification complete

#138 Misc button text updates for Sample Manager (prefer 'Save' and 'Import' over 'Finish')
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/samples/SampleInsertPanel.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.spec.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.tsx
  packages/components/src/components/samples/__snapshots__/SampleSetDetailsPanel.spec.tsx.snap
  packages/components/src/components/user/UserProfile.tsx
Labels: TeamCity test review complete, issue verification complete

#77 EditableGrid Cell render optimization
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/QueryGrid.tsx
  packages/components/src/components/QueryGridPanel.tsx
  packages/components/src/components/editable/Cell.spec.tsx
  packages/components/src/components/editable/Cell.tsx
  packages/components/src/components/editable/EditableGrid.tsx
  packages/components/src/components/editable/EditableGridPanel.tsx
  packages/components/src/components/editable/LookupCell.tsx
  packages/components/src/components/gridbar/GridSelectionBanner.tsx
  packages/components/src/components/gridbar/URLBox.tsx
  packages/components/src/components/gridbar/ViewSelector.tsx
  packages/components/src/components/lineage/LineageGraph.tsx
  packages/components/src/components/lineage/LineageGrid.tsx
  packages/components/src/components/lineage/LineageSummary.tsx
  packages/components/src/components/samples/SampleInsertPanel.tsx
  packages/components/src/global.ts
  packages/components/src/typings/global.d.ts
  packages/components/src/util/global.ts
  packages/components/tsconfig.json
  packages/components/yarn.lock
Labels: TeamCity test review complete, issue verification complete

#142 make validateData on the EditableGrid case insensitive and trim value
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/gridbar/URLBox.tsx
  packages/components/src/models.spec.ts
  packages/components/src/models.ts
Labels: needs TeamCity test review, needs issue verification

#143 Item 6779: Misc Sample Manager bug fixes
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/assay/AssayImportSubMenuItem.tsx
  packages/components/src/components/assay/RunDataPanel.tsx
  packages/components/src/components/assay/__snapshots__/RunDataPanel.spec.tsx.snap
  packages/components/src/components/domainproperties/DomainForm.tsx
  packages/components/src/components/editable/Controls.tsx
  packages/components/src/components/editable/EditableGrid.tsx
  packages/components/src/components/menus/SelectionMenuItem.tsx
  packages/components/src/components/samples/SampleInsertPanel.tsx
  packages/components/src/stories/AssayImportPanels.tsx
  packages/components/src/stories/EditableGridPanel.tsx
Labels: TeamCity test review complete, issue verification complete
