Repository LabKey/labkey-ui-components, pull requests merged in 2020-03, with the labels that each got.

#179 Item 6640: Fixes for List Designer issues targeting LabKey release 20.3
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/domainproperties/list/ListPropertiesPanel.tsx
  packages/components/src/components/domainproperties/models.ts
Labels: TeamCity test review complete

#188 Merge forward changes from release20.3-SNAPSHOT branch
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/domainproperties/list/ListPropertiesPanel.tsx
  packages/components/src/components/domainproperties/models.ts
Labels: TeamCity test review complete

#191 Item 7013: QueriesListing fix for display error message when schema does not exist
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/listing/QueriesListing.tsx
Labels: TeamCity test review complete

#175 Merge Sample Type UI creation and editing into one page
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/domainproperties/actions.ts
  packages/components/src/components/domainproperties/constants.ts
  packages/components/src/components/domainproperties/entities/EntityDetailsForm.tsx
  packages/components/src/components/domainproperties/entities/__snapshots__/EntityDetailsForm.spec.tsx.snap
  packages/components/src/components/domainproperties/list/ListDesignerPanels.spec.tsx
  packages/components/src/components/domainproperties/list/ListDesignerPanels.tsx
  packages/components/src/components/domainproperties/list/__snapshots__/ListDesignerPanels.spec.tsx.snap
  packages/components/src/components/domainproperties/list/models.ts
  packages/components/src/components/domainproperties/models.ts
  packages/components/src/components/domainproperties/samples/SampleTypeDesigner.tsx
  packages/components/src/components/domainproperties/samples/SampleTypePropertiesPanel.spec.tsx
  packages/components/src/components/domainproperties/samples/SampleTypePropertiesPanel.tsx
  packages/components/src/components/domainproperties/samples/__snapshots__/SampleTypePropertiesPanel.spec.tsx.snap
  packages/components/src/components/domainproperties/samples/models.ts
  packages/components/src/components/entities/models.ts
  packages/components/src/components/samples/SampleSetDetailsPanel.spec.tsx
  packages/components/src/components/samples/SampleSetDetailsPanel.tsx
  packages/components/src/components/samples/SampleSetParentAliasRow.spec.tsx
  packages/components/src/components/samples/SampleSetParentAliasRow.tsx
  packages/components/src/components/samples/__snapshots__/SampleSetDetailsPanel.spec.tsx.snap
  packages/components/src/components/samples/__snapshots__/SampleSetParentAliasRow.spec.tsx.snap
  packages/components/src/components/samples/actions.ts
  packages/components/src/constants.ts
  packages/components/src/index.ts
  packages/components/src/stories/SampleTypeDesigner.tsx
  packages/components/src/test/data/property-getDomain-sampleType.json
Labels: needs TeamCity test review, needs issue verification

#193 Issue 39913: Switch from dismissCoreWarnings.api to dismissWarnings.api
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/notifications/actions.ts
Labels: TeamCity test review complete

#182 Item 6835: Data Class designer updates for use in Sample Manager
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/base/models/schemas.ts
  packages/components/src/components/domainproperties/CollapsiblePanelHeader.tsx
  packages/components/src/components/domainproperties/assay/AssayDesignerPanels.tsx
  packages/components/src/components/domainproperties/assay/AssayPropertiesPanel.tsx
  packages/components/src/components/domainproperties/dataclasses/DataClassDesigner.spec.tsx
  packages/components/src/components/domainproperties/dataclasses/DataClassDesigner.tsx
  packages/components/src/components/domainproperties/dataclasses/DataClassPropertiesPanel.spec.tsx
  packages/components/src/components/domainproperties/dataclasses/DataClassPropertiesPanel.tsx
  packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
  packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassPropertiesPanel.spec.tsx.snap
  packages/components/src/components/domainproperties/dataclasses/actions.ts
  packages/components/src/components/domainproperties/dataclasses/models.spec.ts
  packages/components/src/components/domainproperties/dataclasses/models.ts
  packages/components/src/components/domainproperties/list/ListDesignerPanels.spec.tsx
  packages/components/src/components/domainproperties/list/ListDesignerPanels.tsx
  packages/components/src/components/domainproperties/list/ListPropertiesAdvancedSettings.spec.tsx
  packages/components/src/components/domainproperties/list/ListPropertiesPanel.spec.tsx
  packages/components/src/components/domainproperties/list/ListPropertiesPanel.tsx
  packages/components/src/components/domainproperties/list/ListPropertiesPanelFormElements.spec.tsx
  packages/components/src/components/domainproperties/list/SetKeyFieldNamePanel.spec.tsx
  packages/components/src/components/domainproperties/list/models.spec.ts
  packages/components/src/components/entities/EntityTypeDeleteConfirmModal.spec.tsx
  packages/components/src/components/entities/EntityTypeDeleteConfirmModal.tsx
  packages/components/src/components/entities/actions.ts
  packages/components/src/components/samples/actions.ts
  packages/components/src/index.ts
  packages/components/src/stories/DataClassDesigner.tsx
  packages/components/src/stories/EntityTypeDeleteConfirmModal.tsx
  packages/components/src/stories/ListDesignerPanels.tsx
  packages/components/src/stories/mock.tsx
  packages/components/src/test/data/dataClassCategoryType-getQuery.json
  packages/components/src/test/data/dataClassCategoryType-getQueryDetails.json
  packages/components/src/test/data/dataclass-getDomainDetails.json
  packages/components/src/test/data/list-getDomainDetails-withAutoIntPK.json
  packages/components/src/test/data/list-getDomainDetails.json
  packages/components/src/util/BeforeUnload.tsx
Labels: TeamCity test review complete, issue verification complete

#186 Issue 39911: EditableGrid issue with pasting values into a cell that has a lookup that is not public
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/actions.ts
  packages/components/src/components/base/models/model.ts
  packages/components/src/components/editable/Cell.tsx
  packages/components/src/components/forms/QueryFormInputs.spec.tsx
  packages/components/src/components/forms/QueryFormInputs.tsx
  packages/components/src/components/forms/detail/DetailEditRenderer.tsx
  packages/components/src/components/forms/detail/DetailEditing.spec.tsx
  packages/components/src/components/omnibox/actions/Filter.spec.tsx
Labels: TeamCity test review complete

#194 Issue 39968: Cannot update assay result field to "All Samples"
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/domainproperties/SampleFieldOptions.tsx
  packages/components/src/components/domainproperties/models.ts
Labels: needs TeamCity test review, needs issue verification

#207 SiteUsersGridPanel and UserDetails panel prop to hide/show 'Reset Password' button (i.e. allowResetPassword)
  packages/components/package.json
  packages/components/releaseNotes/labkey/components.md
  packages/components/src/components/user/SiteUsersGridPanel.tsx
  packages/components/src/components/user/UserDetailsPanel.spec.tsx
  packages/components/src/components/user/UserDetailsPanel.tsx
  packages/components/src/components/user/__snapshots__/UserDetailsPanel.spec.tsx.snap
  packages/components/src/stories/SiteUsersGridPanel.tsx
Labels: TeamCity test review complete
