Repository LabKey/labkey-ui-components, pull requests merged in 2022-02, with the labels that each got.

#713 Improve sample actions from assay results
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/index.ts
  packages/components/src/internal/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
  packages/components/src/internal/components/domainproperties/samples/__snapshots__/SampleTypeDesigner.spec.tsx.snap
  packages/components/src/internal/components/picklist/AddToPicklistMenuItem.tsx
  packages/components/src/internal/components/picklist/ChoosePicklistModal.tsx
  packages/components/src/internal/components/picklist/PicklistCreationMenuItem.tsx
  packages/components/src/internal/components/picklist/PicklistEditModal.tsx
  packages/components/src/internal/components/samples/APIWrapper.ts
  packages/components/src/internal/components/samples/SampleActionsButton.spec.tsx
  packages/components/src/internal/components/samples/SampleActionsButton.tsx
  packages/components/src/internal/components/samples/actions.spec.ts
  packages/components/src/internal/components/samples/actions.ts
  packages/components/src/internal/schemas.ts
  packages/components/src/public/SchemaQuery.ts
Labels: needs code review, needs issue verification, needs TeamCity test review

#718 Item 9932: Sample Type Insights panel
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/index.ts
  packages/components/src/internal/components/chart/HorizontalBarSection.spec.tsx
  packages/components/src/internal/components/chart/HorizontalBarSection.tsx
  packages/components/src/internal/components/chart/ItemsLegend.spec.tsx
  packages/components/src/internal/components/chart/ItemsLegend.tsx
  packages/components/src/internal/components/chart/__snapshots__/ItemsLegend.spec.tsx.snap
  packages/components/src/internal/components/chart/configs.ts
  packages/components/src/internal/components/chart/utils.spec.ts
  packages/components/src/internal/components/chart/utils.ts
  packages/components/src/internal/components/samples/SampleTypeInsightsPanel.spec.tsx
  packages/components/src/internal/components/samples/SampleTypeInsightsPanel.tsx
  packages/components/src/internal/components/samples/SamplesTabbedGridPanel.tsx
  packages/components/src/internal/schemas.ts
  packages/components/src/theme/charts.scss
  packages/components/src/theme/index.scss
Labels: issue verification complete, TeamCity test review complete

#724 Item 9888: Sample Status help tooltip for grid column headers and details edit field label
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/index.ts
  packages/components/src/internal/components/base/Grid.spec.tsx
  packages/components/src/internal/components/base/Grid.tsx
  packages/components/src/internal/components/base/LabelHelpTip.tsx
  packages/components/src/internal/components/base/models/GridColumn.tsx
  packages/components/src/internal/components/editable/EditableGrid.tsx
  packages/components/src/internal/components/entities/EntityInsertPanel.tsx
  packages/components/src/internal/components/entities/__snapshots__/ParentEntityEditPanel.spec.tsx.snap
  packages/components/src/internal/components/entities/__snapshots__/SingleParentEntityPanel.spec.tsx.snap
  packages/components/src/internal/components/forms/HelpTipRenderer.spec.tsx
  packages/components/src/internal/components/forms/HelpTipRenderer.tsx
  packages/components/src/internal/components/forms/LabelOverlay.tsx
  packages/components/src/internal/components/forms/QuerySelect.tsx
  packages/components/src/internal/components/forms/input/SampleStatusInput.tsx
  packages/components/src/internal/components/forms/input/SelectInput.tsx
  packages/components/src/internal/components/lineage/node/LineageNodeDetail.tsx
  packages/components/src/internal/components/samples/SampleStatusLegend.spec.tsx
  packages/components/src/internal/components/samples/SampleStatusLegend.tsx
  packages/components/src/internal/components/samples/SampleStatusTag.spec.tsx
  packages/components/src/internal/components/samples/SampleStatusTag.tsx
  packages/components/src/internal/components/samples/SamplesEditableGrid.tsx
  packages/components/src/internal/components/samples/utils.spec.tsx
  packages/components/src/internal/components/samples/utils.tsx
  packages/components/src/internal/query/api.ts
  packages/components/src/public/QueryColumn.ts
  packages/components/src/theme/labelHelpTip.scss
  packages/components/src/theme/samples.scss
Labels: issue verification complete, TeamCity test review complete

#727 Issue 44740: Add client side metrics to track if samples/sources are being created via the grid or from file import
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/actions.ts
  packages/components/src/internal/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
  packages/components/src/internal/components/domainproperties/samples/__snapshots__/SampleTypeDesigner.spec.tsx.snap
  packages/components/src/internal/components/entities/EntityInsertPanel.tsx
  packages/components/src/internal/components/entities/constants.ts
  packages/components/src/internal/components/picklist/ChoosePicklistModal.tsx
  packages/components/src/internal/components/picklist/PicklistEditModal.tsx
  packages/components/src/internal/components/productnavigation/ProductLKSDrawer.tsx
  packages/components/src/internal/components/productnavigation/ProductSectionsDrawer.tsx
  packages/components/src/internal/components/search/FindByIdsModal.tsx
  packages/components/src/internal/query/APIWrapper.ts
Labels: TeamCity test review complete

#739 Item 9956: Freezer manager dashboard updates to the freezer listing panel
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/components/ExpandableContainer.tsx
  packages/components/src/internal/components/chart/HorizontalBarSection.tsx
  packages/components/src/internal/components/chart/utils.spec.ts
  packages/components/src/internal/components/chart/utils.ts
  packages/components/src/theme/charts.scss
Labels: issue verification complete, TeamCity test review complete

#736 Core components page update to use QueryModel based EditableGridPanel
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/index.ts
  packages/components/src/internal/components/assay/AssayImportPanels.tsx
  packages/components/src/internal/components/assay/AssayWizardModel.ts
  packages/components/src/internal/components/editable/EditableGridPanel.tsx
  packages/components/src/internal/components/editable/utils.ts
Labels: TeamCity test review complete

#745 Item 9945: Add sample finder related client side metrics
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/components/samples/SampleActionsButton.tsx
  packages/components/src/internal/components/samples/SampleDeleteMenuItem.tsx
  packages/components/src/internal/components/samples/SamplesManageButton.tsx
  packages/components/src/internal/components/samples/models.ts
  packages/components/src/internal/components/search/EntityFieldFilterModal.tsx
  packages/components/src/internal/components/search/FilterCards.tsx
  packages/components/src/internal/components/search/FindAndSearchDropdown.tsx
  packages/components/src/internal/components/search/SampleFinderSection.tsx
  packages/components/src/internal/components/search/utils.ts
Labels: issue verification complete, TeamCity test review complete

#747 Item 9968: Show Freezer List on LKB and LKSM dashboards
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/index.ts
  packages/components/src/internal/app/constants.ts
  packages/components/src/internal/app/utils.ts
  packages/components/src/internal/components/assay/RecentAssayPanel.spec.tsx
  packages/components/src/internal/components/assay/RecentAssayPanel.tsx
  packages/components/src/internal/components/chart/BarChartViewer.tsx
  packages/components/src/internal/url/AppURL.ts
Labels: issue verification complete, TeamCity test review complete
