Repository LabKey/labkey-ui-components, pull requests merged in 2024-05, with the labels that each got.

#1492 Issue 50360: Cross folder bulk edit doesn't work for grid custom view
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/components/entities/actions.ts
Labels: TeamCity test review complete

#1493 Issue 50363: Cross Folder lookup editable grid copy/paste and fill down don't account for containerPath / containerFilter
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/components/editable/EditableGrid.tsx
  packages/components/src/internal/components/editable/actions.test.ts
  packages/components/src/internal/components/editable/actions.ts
Labels: issue verification complete, TeamCity test review complete

#1495 Plate: Well Types and Groups
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/releaseNotes/components.md
  packages/components/src/internal/components/editable/EditableGrid.tsx
  packages/components/src/internal/components/editable/EditableGridLoaderFromSelection.tsx
  packages/components/src/internal/components/editable/models.test.ts
  packages/components/src/internal/components/editable/models.ts
  packages/components/src/internal/renderers.tsx
Labels: Review effort [1-5]: 3
